version: '3.8'

services:
  transformers:
    build:
      context: .
      dockerfile: Dockerfile.transformers
    container_name: transformers_container
    volumes:
      - ./models:/app/models
      - ./scripts:/app/scripts
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    networks:
      - mynetwork
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: